# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 730975930f20c58c91baa31be89dcfe8c50b99e7b74cae0843c1b081bb6b7fb4629d506002e91c561b04304a1f385793850a3d68408c1882964dacf9b956e7c3

test:
  secret_key_base: 3c028b10b0c676fecc47434d06ed32f56ee9613c2ab24977e010a0cb3e567751e90598bcc6a6cf9f6376b52f1b242244a1666f2ede56798d14f46fc43263e0ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
